cvalesares/black_thursday

- Gemfile
- Gemfile.lock
- data/items.csv
- lib/runner.rb
- lib/salesengine.rb
- Reads CSV as it's instantiated
- Creates as array, needs to be hashed in individual classes
> Sales Engine

- lib/merchant_repository.rb
- lib/merchants.rb
- lib/runner.rb
- lib/sales_engine.rb
- spec/merchant_repo_spec.rb
added merchant repository class and spec + placeholder methods that we will need
> feat: add merchant repo & corresponding spec file

- lib/merchant_repository.rb
- lib/merchants.rb
- lib/runner.rb
- lib/sales_engine.rb
- Add methods to Merchant repository
- Reads path sent from SalesEngine
- Converts CSV to hash with merchant id as key
> Feat: add merchant repository

- lib/item_repository.rb
- lib/items.rb
- lib/merchants.rb
- lib/sales_engine.rb
- spec/item_repo_spec.rb
- Add item and merchant classes
- Add from_csv method to parse data
- Add method for SalesEngine to create Item and Merchant objects
- Moved from hashes to array for object storage
> Feat: update sales_engine with merchant and item information

- lib/item_repository.rb
- lib/merchants.rb
- lib/runner.rb
- lib/sales_engine.rb
- spec/item_repo_spec.rb
fix find by id 
fix find by name
add all with description
> feat: "added find methods and test to item_repo"

- lib/merchant_repository.rb
- lib/merchants.rb
- lib/sales_engine.rb
- spec/merchant_repo_spec.rb
- updated sales_engine with proper MerchantRepository path
- was previously instantiating as ItemRepository 
- added methods for find_by_id and find_by name which pass spec
- added methods for find_all_by_name, create, updates, and delete
-  still need to be tested/spec created
- didn't touch the items/item_repo we worked on yesterday
> Feat: add methods to merchant repository and updated sales_engine

- lib/merchant_repository.rb
- lib/merchants.rb
> Feat: add create method to make new instance of Merchant

- lib/item_repository.rb
- lib/items.rb
- spec/item_repo_spec.rb
> "figured out floats, updated methods, put in big decimal"

- lib/merchant_repository.rb
- spec/merchant_repo_spec.rb
Christian knocked out the Item Repo stuff, with the exception being update item. I couldn't think of a way to do it without knowing what attributes it's getting. We also finished up Merchant Repo, but need some help wording our spec for the update item method. The Items class is the only one with lots of red in the spec_harness run. But otherwise we're looking groovy!
> Feat: add methods for delete and update in merchant repo

- lib/items.rb
- spec/item_repo_spec.rb
- spec/items_spec.rb
Items.rb
-updated attributes to correct classes for spec_harness
-unit_price needs to come in as BigDecimal. Still needs work
-unit_price_to_dollars will need to update it to a float when unit_price is BigDecimal
-comments left in unit_price_to_dollars method
Items_spec
-all tests but unit_price pass
-passes all tests but unit_price in spec_harness
> add items spec and update item attributes

- lib/merchants.rb
- lib/sales_analyst.rb
- lib/sales_engine.rb
- spec/merchant_repo_spec.rb
- spec/sales_analyst_spec.rb
add stdev and high items by merchant methods
> feat: add stdev and highest item count methods

- lib/sales_analyst.rb
- spec/sales_analyst_spec.rb
added methods: 
average_item_price, average_average, item_price_stdev, and golden_items
> feat: add average_item_price, average_average, item_price_stdev, + more

- lib/item_repository.rb
- lib/sales_analyst.rb
changed average_average_price_per_merchant and average_item_price_for_merchant(id) to return as bigdecimals instead of floats
> fix: fixes to item_price methods

- lib/item_repository.rb
- lib/items.rb
- lib/sales_analyst.rb
Fixes unit_price issues with item class.
unit_price_to_dollars rounds appropriately
> Fix: unit_price to big decimal

- lib/item_repository.rb
- lib/items.rb
- lib/sales_analyst.rb
- lib/sales_engine.rb
- spec/sales_analyst_spec.rb
Golden items works! Take that standard deviation!
> Fix: golden items returns array of high value items

- lib/invoice_repo.rb
- lib/invoices.rb
- lib/sales_analyst.rb
- lib/sales_engine.rb
- spec/invoice_repo_spec.rb
- spec/item_repo_spec.rb
- spec/items_spec.rb
- spec/merchant_repo_spec.rb
- spec/sales_analyst_spec.rb
We're thigh deep into iteration 2!
Invoice and Invoice Repository are working and green in the spec_harness.
Still need sales_analyst methods though
> Feat: add invoice_repo and invoice_repo_spec

- lib/sales_analyst.rb
- spec/sales_analyst_spec.rb
added methods:
* average_invoices_per_merchant
* invoices_per_merchant
* average_invoices_per_merchant_standard_deviation
* top_merchants_by_invoice_count
* bottom_merchants_by_invoice_count
> feat:add invoice methods to sales_analyst

- lib/invoice_item_repo.rb
- lib/sales_analyst.rb
- spec/invoice_item_repo_spec.rb
- spec/invoice_repo_spec.rb
- spec/merchants_spec.rb
- spec/sales_analyst_spec.rb
Finished beginning of iteration 3, added missing invoice_items.CSV to classes/spec that were missing.
> Finish invoice_item_repo, updated files with missing invoice_items.csv

- lib/invoice_item.rb
- lib/invoice_item_repo.rb
- lib/sales_analyst.rb
- lib/sales_engine.rb
Minor fixes to pass spec harness
> Minor spec harness fixes

- lib/customer.rb
- lib/customer_repo.rb
- lib/items.rb
- lib/sales_analyst.rb
- lib/sales_engine.rb
- spec/customer_repo_spec.rb
- spec/customer_spec.rb
Added customer repo and customer classes
Added customer repo spec
passes all our spec and spec_harness
Still needs work:
customer spec
business intelligence for iteration 3
> Feat: add customer and customer repo classes and spec

- spec/sales_analyst_spec.rb
> Add one more test to sales_analyst spec

- lib/sales_analyst.rb
- spec/sales_analyst_spec.rb
thank Matthew for this. my brain isn't working and I need sleep
> feat: add invoice_total method

- lib/customer_repo.rb
- lib/inspectable.rb
- lib/invoice_item.rb
- lib/invoice_repo.rb
- lib/item_repository.rb
- lib/items.rb
- lib/sales_analyst.rb
- lib/sales_engine.rb
- lib/transaction.rb
- lib/transaction_repository.rb
- spec/customer_repo_spec.rb
- spec/customer_spec.rb
- spec/invoice_item_repo_spec.rb
- spec/invoice_item_spec.rb
- spec/invoice_repo_spec.rb
- spec/invoices_spec.rb
- spec/merchant_repo_spec.rb
- spec/merchants_spec.rb
- spec/sales_analyst_spec.rb
- spec/transaction_repository_spec.rb
- spec/transaction_spec.rb
> cleans up code

- lib/sales_analyst.rb
- spec/sales_analyst_spec.rb
> adds total revenue earners
